defmodule Day11Test do
  use ExUnit.Case

  test "part 1 passes" do
    assert 374 =
             """
             ...#......
             .......#..
             #.........
             ..........
             ......#...
             .#........
             .........#
             ..........
             .......#..
             #...#.....
             """
             |> Day11.PartOne.run()
  end
end
