defmodule Day11Test do
  use ExUnit.Case

  test "part 1 passes" do
    assert 374 =
             """
             ...#......
             .......#..
             #.........
             ..........
             ......#...
             .#........
             .........#
             ..........
             .......#..
             #...#.....
             """
             |> Day11.PartOne.run()
  end

  test "part 2 passes" do
    # 100 times larger
    assert 8410 =
             """
             ...#......
             .......#..
             #.........
             ..........
             ......#...
             .#........
             .........#
             ..........
             .......#..
             #...#.....
             """
             |> Day11.PartTwo.run(100)
  end
end
